### PR TITLE
update xtagctl

### PR DESCRIPTION
**Pull request by BrennanGit**
https://github0.xmos.com/xmos-int/xtagctl/pull/26

### CODE REVIEW

**Review by lucianomartin — COMMENTED** [review]
The audio_test_tools view files already include the xtagctl repo. Is there a reason to duplicate its cloning in the jenkinsfile? I would choose one of two.

**Review by ed-xmos — CHANGES_REQUESTED** [review]
As per Shuchita's comment - it is better to have the version coded into the view file then install -e from the view. I think that will be more obvious to maintainers

**Comment by BrennanGit** [comment]
Agreed, I will make this change across the board.

**Review by shuchitak — APPROVED** [review]

**Review by ed-xmos — APPROVED** [review]
Amazing, ship it

**Pull request merged**
